server {
    listen 80;
    listen [::]:80;
    server_name neeklo-api.modelizmclub.ru;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    root /var/www/modelizmclub-neeklo/backend/public;
    index index.php;
    client_max_body_size 100M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
    }
}
