/**
 * Applies English translations to en.ts for P2 page keys (overrides Russian fallbacks).
 */
import { writeFileSync } from "node:fs";
import { en } from "../src/lib/i18n/locales/en.ts";
import { ru } from "../src/lib/i18n/locales/ru.ts";

type Dict = Record<string, unknown>;

const EN_PAGES: Dict = {
  categoryDetail: {
    metaTitle: "Category — MoDelizM",
    loading: "Loading…",
    notFound: "Category not found.",
    breadcrumbs: "Categories",
    backAria: "Back",
    members: "{{count}} members",
    searchPlaceholder: "Find a room…",
    clearAria: "Clear",
    roomsHeading: "Rooms by subcategory",
    chatLabel: "chat",
    noResults: "Nothing found for «{{query}}»",
    footerNote: "Each subcategory has its own chat, listings and members. Pick a topic so you don't mix with other subjects.",
    roomPreview0: "Who ran the new track this weekend?",
    roomPreview1: "Share your setup — the suspension is floating.",
    roomPreview2: "Selling a kit — will let it go to good hands.",
    roomPreview3: "We're meeting at the club today at 6 PM.",
    roomPreview4: "Posted fresh break-in video in the chat.",
    roomPreview5: "Motor advice — what should I get?",
    roomPreview6: "Build is done — sharing photos.",
    roomPreview7: "Who's racing on Saturday?",
  },
  subcategoryDetail: {
    metaTitle: "Subcategory — MoDelizM",
    loading: "Loading…",
    notFound: "Subcategory not found.",
    breadcrumbs: "Categories",
    backAria: "Back to category",
    online: "{{count}} online",
    tabChat: "Chat",
    tabAds: "Listings",
    tabMembers: "Members",
    closeAria: "Close",
    roomsOf: "«{{name}}» rooms",
    pickSubcategory: "Choose a subcategory",
    hereNow: "Here now",
    dialogOpenFailed: "Could not open chat",
    chatLoadFailed: "Could not load chat",
    roleModerator: "Moderator",
    roleExpert: "Expert",
    offline: "offline",
    writeMessage: "Message",
    searchInMessages: "Search messages…",
    matchCase: "Match case",
    exactMatch: "Exact match",
    prevMatch: "Previous match",
    nextMatch: "Next match",
    closeSearch: "Close search",
    attachmentAlt: "Attachment",
    replyAria: "Reply",
    writePrivateAria: "Send private message",
    cancelReplyAria: "Cancel reply",
    previewAlt: "Preview",
    removeAttachmentAria: "Remove attachment",
    attachPhotoAria: "Attach photo",
    sendFailed: "Could not send message",
    demoMsg1: "Has anyone tried the new suspension settings after the last update?",
    demoMsg2: "Yeah, softened the front — much better on bumps. I'll share photos tonight.",
    demoMsg3: "By the way, club meetup this weekend. Join if you're nearby.",
    demoMsg4: "Motor advice for this class — what to get on a budget?",
    demoIntro: "Hi everyone in «{{name}}» chat! Who's around?",
    demoReply: "Hey! I've been into {{name}} for a while. What are we discussing today?",
    searchInChat: "Search chat",
    chatLoading: "Loading chat…",
    emptyChat: "No messages yet. Be the first to write!",
    replyTo: "Reply: {{name}}",
    writeInSub: "Write in «{{name}}»…",
    noAds: "No listings in «{{name}}» yet",
    noAdsDesc: "This is the local board for this subcategory. Be the first.",
    postAd: "Post a listing",
  },
  settings: {
    metaTitle: "Settings — MoDelizM",
    chooseSection: "Choose a settings section",
    spacesMetaTitle: "My channel & community — MoDelizM",
    accountTitle: "Profile & account",
    publicProfile: "Public profile",
    publicProfileDesc: "Avatar, cover, name, city, interests",
    verified: "Verified",
    notVerified: "Not verified",
    emailMissing: "No email on file",
    changeEmail: "Change email",
    newEmail: "New email",
    changeEmailBtn: "Change email",
    phone: "Phone",
    phoneVerifiedSms: "Verified via SMS",
    phoneNumber: "Phone number",
    sending: "Sending…",
    resendIn: "Resend in {{sec}} sec",
    resendSms: "Resend SMS",
    sendSms: "Send SMS to verify",
    smsCode: "SMS code",
    verifying: "Verifying…",
    confirm: "Confirm",
    loadFailed: "Could not load account data",
    invalidEmail: "Enter a valid email",
    emailUpdated: "Email updated — confirm via the link in the email",
    emailChangeFailed: "Could not change email",
    emailSendFailed: "Could not send email",
    invalidPhone: "Enter a valid phone number",
    smsSent: "Code sent via SMS",
    smsSendFailed: "Could not send SMS",
    invalidSmsCode: "Enter the 6-digit SMS code",
    phoneVerified: "Phone number verified",
    wrongCode: "Wrong code",
    loading: "Loading…",
    emailLabel: "Email",
    verificationSentTo: "A confirmation link was sent to {{email}}.",
    resendVerificationBtn: "Send confirmation email",
    phoneConfirmNote: "Verification is SMS-only. The number is used in billing details and for site actions.",
    navBack: "Settings",
    securityTitle: "Security",
    changePassword: "Change password",
    changePasswordDesc: "Enter your current and new password — the change takes effect immediately without signing out.",
    currentPassword: "Current password",
    newPassword: "New password",
    confirmNewPassword: "Confirm new password",
    changePasswordBtn: "Change password",
    enterCurrentPassword: "Enter your current password",
    passwordMin8: "New password must be at least 8 characters",
    passwordChanged: "Password changed",
    checkCurrentPassword: "Check your current password",
    passwordChangeFailed: "Could not change password",
    demoPasswordChange: "Password change is unavailable in demo mode",
    demoUnavailable: "Unavailable in demo mode",
    sessionsTitle: "Active sessions",
    sessionsDesc: "If you signed in on someone else's device — end all sessions except this one. You'll stay signed in here.",
    logoutOtherDevices: "Sign out on other devices",
    loggedOutOtherDevices: "Signed out on all other devices",
    logoutOthersFailed: "Could not end other sessions",
    blockedUsersTitle: "Blocked users",
    notificationsTitle: "Notifications",
    notificationsDemo: "In demo mode, settings are stored on this device.",
    notificationsDesc: "Choose what you want to be notified about.",
    notificationsLoadFailed: "Could not load settings",
    notificationsSaveFailed: "Could not save",
    notifFriendRequests: "Friend requests",
    notifComments: "Comments",
    notifLikes: "Likes",
    notifMessages: "Messages",
    notifSubscriptionPosts: "Posts from subscriptions",
    appearanceTitle: "Appearance",
    themeTitle: "Theme",
    themeDesc: "«System» switches automatically with your device theme.",
    themeAria: "Theme",
    themeLight: "Light",
    themeLightDesc: "Always light theme",
    themeDark: "Dark",
    themeDarkDesc: "Always dark theme",
    themeSystem: "System",
    themeSystemDesc: "Match device settings",
    dashboardTitle: "Statistics",
    dashboardActive: "Active",
    dashboardViews: "Total views",
    dashboardFavorites: "In favorites",
    dashboardTotal: "Total listings",
    dashboardDynamics: "View trends",
    dashboardDynamicsSoon: "Daily view chart coming soon.",
    statusActive: "Active",
    statusModeration: "Under moderation",
    statusRejected: "With errors",
    statusUnpublished: "Unpublished",
    statusArchived: "Archive",
    statusDraft: "Drafts",
    historyTitle: "View history",
    historyEmpty: "Nothing here yet",
    historyEmptyDesc: "Viewed listings and profiles will appear here",
    historyClear: "Clear history",
    historyKindAd: "Listing",
    historyKindReview: "Review",
    historyKindProfile: "Profile",
    historyKindCommunity: "Community",
    walletTitle: "Wallet",
    walletDemoBalance: "Demo balance",
    walletBalance: "Balance",
    walletHistory: "Transaction history",
    walletEmpty: "No transactions yet",
    ratingTitle: "Rating & reviews",
    ratingBasedOn: "based on {{count}} reviews",
    ratingEmpty: "No reviews yet",
    defaultUser: "User",
    paymentTitle: "Payment methods",
    paymentDesc: "Cards for subscription and paid listings. We don't store the full card number — cards are linked via a secure bank gateway; we only keep a token and the last 4 digits for display.",
    paymentSoon: "Card linking will be available after payment processing is connected",
    paymentDemo: "Payment gateway is not connected in demo mode.",
    paymentEmpty: "No linked cards yet.",
    paymentPrimary: "Primary",
    paymentDelete: "Remove",
    paymentCancel: "Cancel",
    paymentAdd: "Add card",
    paymentAdded: "Card linked",
    paymentAddFailed: "Could not link card",
    paymentBindFailed: "Could not start card linking",
    paymentDeleted: "Card removed",
    paymentDeleteFailed: "Could not remove card",
    cardBrandMir: "MIR",
    cardBrandDefault: "Card",
    requisitesTitle: "Billing details",
    requisitesDesc: "Stored in your account and used for transaction documents. Phone is pulled from",
    requisitesProfileLink: "profile & account",
    requisitesSaved: "Billing details saved",
    requisitesSaveFailed: "Could not save billing details",
    fullName: "Full name",
    fullNamePlaceholder: "John Smith",
    innOptional: "Tax ID (optional)",
    address: "Address",
    addressPlaceholder: "City, street, building",
    save: "Save",
    saving: "Saving…",
    phoneMismatch: "A different number is on file ({{phone}}).",
    changeInProfile: "Change in profile",
    payoutCardTitle: "Payout card",
    payoutCardDesc: "Card number is stored encrypted and used only for manual transfers by an administrator — no automatic payouts via payment gateway.",
    payoutCardSaved: "Saved card •••• {{last4}}",
    payoutCardNew: "New card number (to replace)",
    payoutCardNumber: "Card number",
    payoutCardSavedToast: "Payout card saved",
    payoutCardSaveFailed: "Could not save card",
    payoutCardInvalid: "Enter the full card number (16 digits)",
    payoutDemo: "Saving payout card is unavailable in demo mode",
    spacesTitle: "My channel & community",
    spacesChannel: "Channel",
    spacesNoChannel: "You don't have a channel yet",
    spacesMyChannel: "My channel",
    spacesCreateChannel: "Create channel",
    spacesCommunity: "Community",
    spacesNoCommunity: "Create your community by city or niche topic",
    spacesMyCommunity: "My community",
    spacesCreateCommunity: "Create community",
  },
  onboarding: {
    metaTitle: "Choose interests — MoDelizM",
    skip: "Skip",
    step: "Step 1 of 1",
    title: "What are you interested in?",
    subtitle: "Pick categories — your feed, chats and listings will be tailored to them. You can change this later in your profile.",
    selected: "Selected: {{count}} of {{total}}",
    continue: "Continue →",
    selectOne: "Select at least one category",
    done: "Done! Your feed is tailored to your interests",
    interestRcCars: "RC cars",
    interestRcCarsDesc: "Nitro, electric, drift, rally, crawlers",
    interestRcAir: "RC aircraft",
    interestRcAirDesc: "Gliders, aerobatics, scale models",
    interestFpv: "Drones / FPV",
    interestFpvDesc: "Racing, freestyle, cinematic",
    interestRcBoats: "Boats & ships",
    interestRcBoatsDesc: "Yachts, speedboats, scale replicas",
    interestElectronics: "Electronics",
    interestElectronicsDesc: "ESCs, motors, firmware",
    interestStatic: "Static modeling",
    interestStaticDesc: "Assembly, painting, dioramas",
    interestTrade: "Buy & sell",
    interestTradeDesc: "Parts and ready-made models",
    interestEvents: "Events & races",
    interestEventsDesc: "Local clubs and championships",
  },
  subscription: {
    metaTitle: "Subscription — MoDelizM",
    eyebrow: "PLANS",
    title: "MoDelizM subscription",
    subtitle: "One set of features — pick a term. All plans give the same platform access.",
    activePlan: "«{{name}}» subscription is active",
    active: "active",
    validUntil: "Valid until {{date}}",
    daysLeft: "until expiry",
    freeListings: "Free listings: {{left}} of {{limit}}",
    subscribe: "Subscribe",
    oneTimeTitle: "One-time listing",
    oneTimeDesc: "One listing for 99 ₽ — no subscription or commitment. For when you need a single post, not ongoing access.",
    oneTimeCta: "Post listing",
    paySoon: "Payment will be available after payment processing is connected",
    paySoonDesc: "One-time listing — 99 ₽",
    paySoonPlan: "Plan: {{name}}",
    loginRequired: "Sign in to subscribe",
    testActivated: "Subscription activated (test mode)",
    testConfirmed: "Payment confirmed (test mode)",
    payCreateFailed: "Could not create payment. Try again later.",
    oneTimePaid: "Listing paid (test mode) — available when creating a listing",
    paySuccess: "Payment successful — subscription activating",
    payFailed: "Payment not completed",
    defaultPlanName: "Subscription",
    day: "day",
    days2: "days",
    days5: "days",
  },
  help: {
    metaTitle: "Help — MoDelizM",
    eyebrow: "HELP",
    title: "Knowledge base",
    subtitle: "Answers to common questions about the MoDelizM platform",
    searchPlaceholder: "Search the knowledge base...",
    searchPlaceholderShort: "Search questions",
    all: "All",
    nothingFound: "Nothing found. Try a different search.",
    contactTitle: "Didn't find an answer? Contact us",
    contactDesc: "Write to us — we'll reply within one business day",
    fillAllFields: "Fill in all fields",
    sent: "Message sent! We'll reply within 24 hours.",
    sendFailed: "Could not send",
    topic: "Topic",
    selectTopic: "Choose a topic",
    topicPayment: "Payment issue",
    topicListing: "Listing question",
    topicAccount: "Account issue",
    topicReport: "Report a user",
    topicSuggestion: "Suggestion",
    topicOther: "Other",
    email: "Email",
    emailPlaceholder: "Your email",
    message: "Message",
    messagePlaceholder: "Describe the issue in detail...",
    send: "Send",
  },
  legal: {
    rulesMetaTitle: "Community rules — MoDelizM",
    rulesMetaDescription: "Rules for posting, communication and behavior in the MoDelizM community.",
    rulesTitle: "Community rules",
    rulesSubtitle: "These rules help everyone enjoy MoDelizM comfortably.",
    rule1Title: "Respect members",
    rule1Text: "Insults, threats, hate speech and discrimination of any kind are prohibited.",
    rule2Title: "On-topic content",
    rule2Text: "Post modeling-related material: models, tech, reviews, events, tutorials.",
    rule3Title: "No spam or manipulation",
    rule3Text: "Mass messaging, reaction farming, fake reviews and off-listing ads are prohibited.",
    rule4Title: "Accuracy",
    rule4Text: "Do not publish knowingly false information about products, sellers or brands.",
    rule5Title: "Copyright",
    rule5Text: "Do not post others' content without permission and attribution.",
    rule6Title: "Moderation",
    rule6Text: "Moderators may hide rule-breaking content. Repeated violations lead to account suspension.",
    questions: "Questions and reports:",
    privacyMetaTitle: "Privacy policy — MoDelizM",
    privacyTitle: "Data processing policy",
    privacyDemo: "Demo version. The official policy will be published at production launch.",
    privacy1Title: "1. What data we collect",
    privacy1Text: "Name, email, avatar, content you publish, and technical session data (IP, device, browser).",
    privacy2Title: "2. Why we need it",
    privacy2Text: "Authentication, feed personalization, fraud prevention, service quality analytics.",
    privacy3Title: "3. Third-party sharing",
    privacy3Text: "We do not sell your data. Sharing is only required by law or with your explicit consent.",
    privacy4Title: "4. Storage and deletion",
    privacy4Text: "Data is kept while your account is active. You can delete your account and related data in profile settings or on request.",
    privacy5Title: "5. Cookies",
    privacy5Text: "We use cookies for authentication, UI preferences and basic analytics.",
    privacy6Title: "6. Contact",
    privacy6Text: "Data processing requests:",
  },
  info: {
    metaTitle: "Information — MoDelizM",
    badge: "Information",
    backHome: "Home",
    preparingTitle: "Document in preparation",
    preparingDesc: "The full document will appear at production launch.",
    writeSupport: "Contact support",
    fallbackTitle: "Page in preparation",
    fallbackDesc: "This section is coming soon. You can return home or contact support for now.",
    aboutTitle: "About us",
    aboutDesc: "MoDelizM is a marketplace, feed and community for modelers in Russia. We bring together people who build, fly and race.",
    companyTitle: "About the company",
    companyDesc: "Legal and organizational information about MoDelizM. Company details will appear at production launch.",
    partnersTitle: "For partners",
    partnersDesc: "Partnerships with shops, brands and clubs. Joint promos, showcases and brand channels for the modeling world.",
    advertisingTitle: "Advertising",
    advertisingDesc: "Promotion formats on the platform: banners, boosted listings and brand channels. Media kit in preparation.",
    complianceTitle: "Compliance",
    complianceDesc: "Principles for legal compliance, content moderation and safe transactions.",
    consentTitle: "Personal data consent",
    consentDesc: "Terms for processing personal data of MoDelizM platform users.",
    supportTitle: "Support",
    supportDesc: "We're available daily 10:00–20:00 MSK. Write to us — we'll help with your account, listings or transactions.",
    feedbackTitle: "Feedback",
    feedbackDesc: "Your ideas and feedback make the platform better. Leave a review or report an issue.",
    contactsTitle: "Contacts",
    contactsDesc: "Reach us: support@modelizmclub.ru, 8 800 000-00-00, Mon–Sun 10:00–20:00 MSK. Social links will appear when official channels launch.",
    securityTitle: "Security",
    securityDesc: "Safe transaction principles, listing moderation and personal data protection on MoDelizM. Full policy at production launch.",
    returnHome: "Return home",
  },
  reviews: {
    metaTitle: "Reviews — MoDelizM",
    detailMetaTitle: "Review — MoDelizM",
    searchPlaceholder: "Search reviews",
    searchAria: "Search reviews",
    searchResults: "Search results",
    allReviews: "All reviews",
    allCategory: "All",
    newReleases: "New releases",
    loading: "Loading…",
    nothingFound: "Nothing found",
    nothingFoundDesc: "Try a different search or category.",
    uploadMetaTitle: "Upload review — MoDelizM",
    checkingAccess: "Checking access…",
    accessDenied: "Access restricted",
    accessDeniedDesc: "Only platform administrators can upload reviews.",
    newReview: "New review",
    uploadVideo: "Upload video (mp4)",
    uploadPoster: "Cover (optional)",
    titlePlaceholder: "Review title",
    descriptionPlaceholder: "Description",
    tagsPlaceholder: "Tags separated by commas",
    featuredCarousel: "Show in «Recommended» carousel",
    publishing: "Publishing…",
    publish: "Publish review",
    published: "Review published",
    publishFailed: "Could not publish review",
    loginRequired: "Sign in to watch reviews",
    notFound: "Review not found",
    loadFailed: "Could not load review",
    notFoundDesc: "It may have been removed or the link is outdated.",
    toReviews: "Back to reviews",
    breadcrumb: "Reviews",
    watchAria: "Watch",
    dataSaver: "Data saver — video loads on tap",
    views: "{{count}} views",
    authorLabel: "Review author",
    comments: "Comments",
    similar: "Similar reviews",
    likeFailed: "Could not like",
    commentFailed: "Could not post comment",
  },
};

function deepMerge(base: Dict, overlay: Dict): Dict {
  const out = { ...base };
  for (const [k, v] of Object.entries(overlay)) {
    if (v && typeof v === "object" && !Array.isArray(v) && out[k] && typeof out[k] === "object" && !Array.isArray(out[k])) {
      out[k] = deepMerge(out[k] as Dict, v as Dict);
    } else {
      out[k] = v;
    }
  }
  return out;
}

function toTs(obj: unknown, indent = 0): string {
  const pad = "  ".repeat(indent);
  if (typeof obj === "string") return JSON.stringify(obj);
  if (Array.isArray(obj)) {
    return "[\n" + obj.map((v) => pad + "  " + toTs(v, indent + 1)).join(",\n") + "\n" + pad + "]";
  }
  const lines = Object.entries(obj as Dict).map(([k, v]) => {
    const key = /^[a-zA-Z_$][\w$]*$/.test(k) ? k : JSON.stringify(k);
    return `${pad}  ${key}: ${toTs(v, indent + 1)}`;
  });
  return "{\n" + lines.join(",\n") + "\n" + pad + "}";
}

const mergedPages = deepMerge(en.pages as Dict, EN_PAGES);
const mergedEn = { ...en, pages: mergedPages };

// Ensure en has all ru keys (structure)
const fullEn = deepMerge(ru as unknown as Dict, mergedEn as unknown as Dict) as typeof ru;

writeFileSync(
  "src/lib/i18n/locales/en.ts",
  `import type { TranslationSchema } from "./ru";\n\nexport const en: TranslationSchema = ${toTs(fullEn)};\n`,
);
writeFileSync(
  "src/lib/i18n/locales/zh.ts",
  `import type { TranslationSchema } from "./ru";\n\nexport const zh: TranslationSchema = ${toTs(fullEn)};\n`,
);
console.log("Patched en.ts and zh.ts with P2 English translations");
