/**
 * Applies English translations to en.ts for P1 page keys (overrides Russian fallbacks).
 */
import { writeFileSync } from "node:fs";
import { en } from "../src/lib/i18n/locales/en.ts";
import { ru } from "../src/lib/i18n/locales/ru.ts";

type Dict = Record<string, unknown>;

const EN_PAGES: Dict = {
  communityDetail: {
    metaTitle: "Community — MoDelizM",
    tabPosts: "Posts",
    tabDiscussions: "Discussions",
    tabEvents: "Events",
    tabMembers: "Members",
    tabAbout: "About",
    notFoundTitle: "Community not found",
    notFoundDesc: "It may have been removed or the link is incorrect",
    allCommunities: "All communities",
    reportAria: "Report community",
    manageTitle: "Manage community",
    members: "{{count}} members",
    youOwner: "You are the owner",
    youSubscribed: "Subscribed",
    subscribe: "Subscribe",
    proposeProject: "Submit a project",
    share: "Share",
    wantOwnCommunity: "I want my own community",
    emptyPosts: "No posts yet",
    emptyPostsDesc: "Community posts will appear here",
    discussionsHeading: "Discussions",
    emptyDiscussions: "No discussions yet",
    emptyDiscussionsDesc: "Start the first topic in this community",
    emptyEvents: "No events yet",
    emptyEventsDesc: "Races and meetups will appear here soon",
    membersHeading: "Members",
    membersUnavailable: "Member list unavailable",
    aboutHeading: "About the community",
    adminLabel: "Admin: {{name}}",
    repliesCount: "{{count}} replies · {{activity}}",
    attendeesGoing: "{{count}} going",
    signUp: "Sign up",
    roleAdmin: "Administrator",
    membersOnline: "Members online",
    upcomingEvents: "Upcoming events",
    similarCommunities: "Similar communities",
    requestSent: "Request sent",
    demoSignupNote: "Demo mode: event signup saved. Production will show a participant form and confirmation.",
    gotIt: "Got it",
    reportSuffix: " (community)",
    reportDesc: "You are reporting community «{{name}}». Describe the issue.",
  },
  channels: {
    metaTitle: "Channels — MoDelizM",
    metaDescription: "Subscribe to brand, shop, author and expert channels: news, reviews and offers.",
    title: "Channels",
    subtitle: "News, reviews and announcements — from channel owners only",
    searchPlaceholder: "Search channels",
    emptyTitle: "No channels yet",
    emptySearchDesc: "Try a different search",
    emptyDesc: "Create a channel for posts — it will appear under My channels",
    createChannel: "Create channel",
    sectionMine: "My channels",
    sectionMineSub: "Channels where you are owner or author",
    sectionSubscriptions: "My subscriptions",
    sectionSubscriptionsSub: "Channels you subscribed to",
    sectionPopular: "Popular channels",
    sectionPopularSub: "Most subscribers",
    sectionNew: "New channels",
    sectionNewSub: "Recently created",
    subscribeFailed: "Could not update subscription",
    kindOfficial: "Official",
    kindBrand: "Brand",
    kindShop: "Shop",
    kindAuthor: "Author",
    kindExpert: "Expert",
    kindDefault: "Channel",
    postKindNews: "News",
    postKindReview: "Review",
    postKindAnnounce: "Announcement",
    postKindPromo: "Special offer",
  },
  channelDetail: {
    metaTitle: "Channel — MoDelizM",
    notFoundTitle: "Channel not found",
    notFoundDesc: "It may have been removed or the link is incorrect",
    allChannels: "All channels",
    subscribeFailed: "Could not update subscription",
    settingsTitle: "Channel settings",
    tabAbout: "About",
    filterPublished: "Published only",
    filterAll: "All",
    statusPublished: "Published",
    statusModeration: "Under review",
    statusRejected: "Rejected",
    postAlt: "Channel post",
    postSentModeration: "Post sent for moderation",
    postPublished: "Post published",
    publishFailed: "Could not publish post",
    moderationAfterSend: "Moderated after submit",
    publishesImmediately: "Publishes immediately",
    addVideo: "Add video",
    publishing: "Publishing…",
    publish: "Publish",
    moderationPendingDesc: "Subscribers will see the post after moderator approval. Track status in the Posts tab.",
    publishedDesc: "The post is already visible to subscribers and duplicated to the site feed.",
    rulePremodTitle: "Pre-moderation",
    rulePublishTitle: "Publishing",
    rulePremodText: "Every post is reviewed before publishing. Subscribers cannot see it until approved.",
    rulePublishText: "Owner posts publish immediately and are visible to subscribers.",
    ruleNoChatTitle: "No chat",
    ruleNoChatText: "Subscribers cannot write to the feed — this is a one-way channel.",
    ruleNoSpamTitle: "No off-topic spam",
    ruleNoSpamText: "Third-party links and ads without approval are rejected.",
    statSubscribers: "Subscribers",
    statPosts: "Posts",
    statSince: "Since",
    createPostPlaceholder: "Create a post…",
    newPost: "New post",
    emptyPosts: "No posts yet",
    emptyPostsChannel: "No posts in this channel yet",
    tabPosts: "Posts",
    publicChannelNote: "This is a public channel: only the owner publishes. Subscribers read and cannot post to the feed.",
    ownerViewTitle: "Owner view",
    ownerViewDesc: "Shows posts under moderation and rejected",
    subscribersCount: "{{count}} subscribers",
    ownerOnlyPublish: "Owner publishes only",
    youAreOwner: "You are the channel owner",
    wantOwnChannel: "I want my own channel",
    rejectionReasonTitle: "Rejection reason",
    postTextPlaceholder: "{{kind}} text for subscribers…",
    aboutTitle: "Description",
    aboutExtra: "This channel publishes {{kind}} content: news, reviews, announcements and special offers for subscribers. Subscribe to get new posts in your feed.",
    ownerSection: "Owner",
    ownerProfileAria: "Profile {{name}}",
    ownerLeads: "{{kind}} · runs channel «{{name}}»",
    channelCreated: "Channel created {{date}}.",
    publicationRules: "Publishing rules",
  },
  profile: {
    metaTitle: "Profile — MoDelizM",
    tabPosts: "Posts",
    tabAds: "Listings",
    tabCommunities: "Communities",
    tabInvited: "Invited",
    tabBlocked: "Blocked",
    tabAbout: "About",
    editProfile: "Edit profile",
    write: "Message",
    addFriend: "Add friend",
    inFriends: "Friends",
    requestSent: "Request sent",
    follow: "Follow",
    unfollow: "Unfollow",
    notFound: "User not found",
    save: "Save",
    cancel: "Cancel",
    emptyPosts: "No posts yet",
    emptyAds: "No listings yet",
    emptyCommunities: "No communities yet",
    earlyMemberBadge: "One of the first 100 club members",
    requestSent: "Request sent",
    requestFailed: "Could not send request",
    writeMessage: "Send message",
    writeMessageAria: "Send message",
    dialogOpenFailed: "Could not open chat",
    followed: "You followed",
    unfollowed: "You unfollowed",
    followFailed: "Could not update subscription",
    followAria: "Follow",
    counterPosts: "Posts",
    counterAds: "Listings",
    counterFriends: "Friends",
    counterCommunities: "Communities",
    emptyPostsShort: "No posts",
    emptyAdsShort: "No listings",
    emptyAdsFiltered: "No listings with this status",
    emptyCommunitiesShort: "Not in any communities",
    profileUpdated: "Profile updated",
    profileSaveFailed: "Could not save profile",
    fieldName: "Name",
    fieldCity: "City",
    cityPlaceholder: "City",
    fieldBio: "About",
    bioPlaceholder: "Tell us about yourself",
    fieldInterests: "Interests",
    removeInterest: "Remove",
    addInterest: "Add interest",
    fileProcessFailed: "Could not process file",
    avatarUpdated: "Profile photo updated",
    avatarUploadFailed: "Could not upload photo",
    checkFileFormat: "Check file format and size",
    photoRemoved: "Photo removed",
    photoRemoveFailed: "Could not remove photo",
    adFilterAll: "All",
    adFilterActive: "Active",
    adFilterModeration: "Under moderation",
    adFilterRejected: "Rejected",
    adFilterArchived: "Archive",
    adBadgeActive: "Active",
    adBadgeModeration: "Under moderation",
    adBadgeRejected: "Rejected",
    adBadgeArchived: "Archived",
    earlyMember100: "★ First 100",
    createListing: "Create listing",
    emptyAbout: "This user has not filled in their About section yet",
    editProfileTitle: "Edit profile",
    changePhoto: "Change photo",
    uploadPhoto: "Upload photo",
    processing: "Processing…",
    deletePhoto: "Remove",
    cropAvatarTitle: "Crop profile photo",
    cropCoverTitle: "Crop cover photo",
    changeCover: "Change cover",
    coverUpdated: "Cover updated",
    coverUploadFailed: "Could not upload cover",
  },
  user: {
    metaTitle: "Profile — MoDelizM",
    loading: "Loading…",
    notFound: "User not found",
    toFriends: "Back to friends",
    dialogOpenFailed: "Could not open chat",
  },
  adDetail: {
    metaTitle: "Listing — MoDelizM",
    notFoundTitle: "Listing not found",
    notFoundDesc: "It may have been sold, unpublished or the link is outdated.",
    toList: "Back to listings",
    loginForPhone: "Sign in to view phone number",
    phoneFailed: "Could not get phone number",
    sellerDialogFailed: "Could not open chat with seller",
    dialogOpenFailed: "Could not open chat",
    loginToMessage: "Sign in to message the seller",
    ownListing: "This is your listing",
    linkCopied: "Link copied",
    copyFromBar: "Copy the link from the address bar",
    loginForFavorite: "Sign in to add to favorites",
    favoriteFailed: "Could not update favorites",
    removedFromFavorites: "Removed from favorites",
    addedToFavorites: "Added to favorites",
    noDescription: "No description.",
    specCategory: "Category",
    specCondition: "Condition",
    specCity: "City",
    deliveryCdek: "📦 Delivery: {{choice}}",
    deliveryPost: "🚚 Delivery: {{choice}}",
    deliveryPickup: "🤝 {{choice}}",
    deliveryGeneric: "📦 Pickup method: {{choice}}",
    loadFailedTitle: "Could not load listing",
    loadFailedDesc: "Check your connection and try again.",
    backToList: "Back to list",
    listingsBreadcrumb: "Listings",
    descriptionHeading: "Description",
    deliveryHeading: "Delivery",
    sellerIntro: "Hello! I'm writing about «{{title}}». Is it still available?",
  },
  adsNew: {
    metaTitle: "New listing — MoDelizM",
    photoRequiredTitle: "Add at least one photo",
    photoRequiredDesc: "You need at least 1 photo to publish a listing.",
    stepPhoto: "Photos",
    stepData: "Details",
    stepPreview: "Preview",
    loadFailed: "Could not load listing for editing",
    selectCategory: "Select a category",
    updated: "Listing updated",
    quoteFailed: "Could not calculate placement cost. Try again.",
    paySoon: "Payments will be available after payment processing is connected",
    paySuccess: "Payment successful — listing submitted for publication",
    sentModeration: "Listing sent for moderation",
    published: "Listing published",
    saveFailed: "Could not save changes",
    publishFailed: "Could not publish listing",
    free: "Free",
    saveChanges: "Save changes",
    calculating: "Calculating…",
    publishFree: "Publish for free",
    publish: "Publish",
    calculatingCost: "Calculating placement cost…",
    paidPlacement: "Placement — {{price}}. After payment the listing goes to moderation.",
    freePlacement: "Fill out the form and publish — placement is free for now.",
    saving: "Saving…",
    publishing: "Publishing…",
    photosHeading: "Photos",
    photosDesc: "At least 1 photo, up to {{max}}. First photo is the cover. Drag to reorder.",
    listingType: "Listing type",
    statusSelling: "Selling",
    statusSellingDesc: "I want to sell an item",
    statusBuying: "Buying",
    statusBuyingDesc: "Looking to buy",
    statusExchange: "Exchange",
    statusExchangeDesc: "Open to trade",
    descriptionBlock: "Description",
    titleLabel: "Title",
    titleMinError: "At least 4 characters",
    titlePlaceholder: "Picco .21 engine for 1:8 buggy",
    descLabel: "Detailed description",
    descMinError: "At least 20 characters",
    descPlaceholder: "Condition, usage history, what's included…",
    paramsBlock: "Details",
    priceLabel: "Price, ₽",
    priceError: "Enter a price",
    conditionLabel: "Condition",
    conditionHint: "Describe the condition in the listing description.",
    categoryLabel: "Category",
    subcategoryLabel: "Subcategory",
    contactsBlock: "Contact & delivery",
    cityError: "Select a city from the list",
    cityPlaceholder: "City name",
    contactLabel: "Contact",
    contactError: "Enter a phone number",
    deliveryMethodsLabel: "Delivery methods",
    previewHeading: "Preview",
    previewDesc: "This is how buyers will see your listing.",
    publishErrorBanner: "Could not publish listing. Check the form and tap «{{label}}» again.",
    titleFallback: "Listing title",
    descFallback: "Description not filled in.",
    moderationNoteFree: "Placement is free — the listing will go to moderation after publishing.",
    moderationNotePaid: "To pay {{price}} ₽. After payment the listing goes to moderation (usually within 60 minutes).",
    moderationNoteDefault: "After publishing the listing goes to moderation (usually within 60 minutes).",
    promocodeLabel: "Promo code",
    basePrice: "Base price: {{price}} ₽",
    promoDiscount: "Promo discount: −{{price}} ₽",
    freeListingsRemaining: "Free listings this month: {{count}}",
    backToListings: "Back to listings",
    newListingTitle: "New listing",
    back: "Back",
    next: "Next",
    payAndPublish: "Pay {{price}} and publish",
    priceMaxError: "Enter a valid price — maximum {{max}} ₽",
  },
  myAds: {
    metaTitle: "My listings — MoDelizM",
    title: "My listings",
    postListing: "Post a listing",
    searchPlaceholder: "Search listings",
    selected: "Selected: {{count}}",
    cancelSelection: "Cancel selection",
    tabActive: "Active",
    tabModeration: "Under moderation",
    tabRejected: "With errors",
    tabUnpublished: "Unpublished",
    tabArchived: "Archive",
    tabDeleted: "Deleted",
    tabDraft: "Drafts",
    statActive: "Active",
    statViews: "Views",
    statLikes: "Likes",
    statOnSale: "For sale",
    chipAll: "All",
    chipNew: "New",
    chipUsed: "Used",
    chipDelivery: "Delivery available",
    clearSearch: "Clear",
    filters: "Filters",
    resetFilters: "Reset filters",
    filterCategory: "Category",
    filterCity: "City",
    filterPeriod: "Period",
    filterCondition: "Condition",
    conditionNew: "New",
    conditionUsed: "Used",
    filterPriceFrom: "Price from, ₽",
    filterPriceTo: "Price to, ₽",
    filterDelivery: "Delivery",
    filterPhotos: "Photos",
    filterSort: "Sort",
    emptyActive: "No active listings",
    emptyActiveDesc: "Create your first — it's free and takes 2 minutes.",
    emptyModeration: "Nothing under moderation",
    emptyModerationDesc: "Listings awaiting moderator review will appear here.",
    emptyRejected: "No listings with errors",
    emptyRejectedDesc: "Listings rejected by moderation will appear here.",
    emptyUnpublished: "No unpublished listings",
    emptyUnpublishedDesc: "Listings ready to publish will appear here.",
    emptyArchived: "Archive is empty",
    emptyArchivedDesc: "Archived listings can be restored anytime.",
    emptyDeleted: "No deleted listings",
    emptyDeletedDesc: "Deleted listings are kept for 30 days.",
    emptyDraft: "No drafts",
    emptyDraftDesc: "Incomplete listings are auto-saved as drafts.",
    subtitle: "Manage listings, stats and archive",
    allCategories: "All categories",
    allCities: "All cities",
    periodAll: "All time",
    periodToday: "Today",
    period7d: "7 days",
    period30d: "30 days",
    anyCondition: "Any",
    deliveryAny: "Any",
    deliveryYes: "Delivery available",
    deliveryNo: "No delivery",
    photoAny: "Doesn't matter",
    photoYes: "With photos",
    photoNo: "Without photos",
    sortNew: "Newest first",
    sortOld: "Oldest first",
    sortViews: "Most views",
    sortLikes: "Most likes",
    sortPriceAsc: "Price ↑",
    sortPriceDesc: "Price ↓",
    sortUpdated: "Recently updated",
    archiveSelected: "Archive",
    deleteSelected: "Delete",
  },
  messenger: {
    metaTitle: "Messenger — MoDelizM",
    openPhotoFullscreen: "Open photo fullscreen",
    listingLabel: "Listing",
    forwardedFrom: "Forwarded from {{name}}",
    deleteForAllConfirm: "Delete this message for everyone? This cannot be undone.",
    deleteChatFailed: "Could not delete chat",
    userUnblocked: "{{name}} unblocked",
    blockConfirm: "Block {{name}}? You will no longer receive messages from them.",
    userBlockedToast: "{{name}} blocked",
    clearHistoryConfirm: "Clear chat history? This cannot be undone.",
    channelSubscribed: "Subscribed",
  },
};

function deepMerge(base: Dict, overlay: Dict): Dict {
  const out = { ...base };
  for (const [k, v] of Object.entries(overlay)) {
    if (v && typeof v === "object" && !Array.isArray(v) && out[k] && typeof out[k] === "object" && !Array.isArray(out[k])) {
      out[k] = deepMerge(out[k] as Dict, v as Dict);
    } else {
      out[k] = v;
    }
  }
  return out;
}

function toTs(obj: unknown, indent = 0): string {
  const pad = "  ".repeat(indent);
  if (typeof obj === "string") return JSON.stringify(obj);
  if (Array.isArray(obj)) {
    return "[\n" + obj.map((v) => pad + "  " + toTs(v, indent + 1)).join(",\n") + "\n" + pad + "]";
  }
  const lines = Object.entries(obj as Dict).map(([k, v]) => {
    const key = /^[a-zA-Z_$][\w$]*$/.test(k) ? k : JSON.stringify(k);
    return `${pad}  ${key}: ${toTs(v, indent + 1)}`;
  });
  return "{\n" + lines.join(",\n") + "\n" + pad + "}";
}

const mergedPages = deepMerge(en.pages as Dict, EN_PAGES);
const mergedEn = { ...en, pages: mergedPages };

// Ensure en has all ru keys (structure)
const fullEn = deepMerge(ru as unknown as Dict, mergedEn as unknown as Dict) as typeof ru;

writeFileSync(
  "src/lib/i18n/locales/en.ts",
  `import type { TranslationSchema } from "./ru";\n\nexport const en: TranslationSchema = ${toTs(fullEn)};\n`,
);
writeFileSync(
  "src/lib/i18n/locales/zh.ts",
  `import type { TranslationSchema } from "./ru";\n\nexport const zh: TranslationSchema = ${toTs(fullEn)};\n`,
);
console.log("Patched en.ts and zh.ts with P1 English translations");
