/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RecoverRouteImport } from './routes/recover'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MyAdsRouteImport } from './routes/my-ads'
import { Route as MessengerRouteImport } from './routes/messenger'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DiagRouteImport } from './routes/diag'
import { Route as CommunitiesRouteImport } from './routes/communities'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdsRouteImport } from './routes/ads'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as ReviewsIndexRouteImport } from './routes/reviews.index'
import { Route as CommunitiesIndexRouteImport } from './routes/communities.index'
import { Route as ChannelsIndexRouteImport } from './routes/channels.index'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as AdsIndexRouteImport } from './routes/ads.index'
import { Route as UserIdRouteImport } from './routes/user.$id'
import { Route as SettingsWalletRouteImport } from './routes/settings.wallet'
import { Route as SettingsRequisitesRouteImport } from './routes/settings.requisites'
import { Route as SettingsRatingRouteImport } from './routes/settings.rating'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsHistoryRouteImport } from './routes/settings.history'
import { Route as SettingsAccountRouteImport } from './routes/settings.account'
import { Route as ReviewsUploadRouteImport } from './routes/reviews.upload'
import { Route as ReviewsIdRouteImport } from './routes/reviews.$id'
import { Route as LegalRulesRouteImport } from './routes/legal.rules'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as InfoSlugRouteImport } from './routes/info.$slug'
import { Route as CommunitiesIdRouteImport } from './routes/communities.$id'
import { Route as ChannelIdRouteImport } from './routes/channel.$id'
import { Route as CategoriesIdRouteImport } from './routes/categories.$id'
import { Route as AdsNewRouteImport } from './routes/ads.new'
import { Route as AdsIdRouteImport } from './routes/ads.$id'
import { Route as AdminDesignSystemRouteImport } from './routes/admin.design-system'
import { Route as CategoriesIdIndexRouteImport } from './routes/categories.$id.index'
import { Route as CategoriesIdSubIdRouteImport } from './routes/categories.$id.$subId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverRoute = RecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAdsRoute = MyAdsRouteImport.update({
  id: '/my-ads',
  path: '/my-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const MessengerRoute = MessengerRouteImport.update({
  id: '/messenger',
  path: '/messenger',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagRoute = DiagRouteImport.update({
  id: '/diag',
  path: '/diag',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesRoute = CommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsRoute = AdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const ReviewsIndexRoute = ReviewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReviewsRoute,
} as any)
const CommunitiesIndexRoute = CommunitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommunitiesRoute,
} as any)
const ChannelsIndexRoute = ChannelsIndexRouteImport.update({
  id: '/channels/',
  path: '/channels/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CategoriesRoute,
} as any)
const AdsIndexRoute = AdsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdsRoute,
} as any)
const UserIdRoute = UserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsWalletRoute = SettingsWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsRequisitesRoute = SettingsRequisitesRouteImport.update({
  id: '/requisites',
  path: '/requisites',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsRatingRoute = SettingsRatingRouteImport.update({
  id: '/rating',
  path: '/rating',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsHistoryRoute = SettingsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsRoute,
} as any)
const ReviewsUploadRoute = ReviewsUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => ReviewsRoute,
} as any)
const ReviewsIdRoute = ReviewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReviewsRoute,
} as any)
const LegalRulesRoute = LegalRulesRouteImport.update({
  id: '/legal/rules',
  path: '/legal/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoSlugRoute = InfoSlugRouteImport.update({
  id: '/info/$slug',
  path: '/info/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesIdRoute = CommunitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CommunitiesRoute,
} as any)
const ChannelIdRoute = ChannelIdRouteImport.update({
  id: '/channel/$id',
  path: '/channel/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIdRoute = CategoriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CategoriesRoute,
} as any)
const AdsNewRoute = AdsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdsRoute,
} as any)
const AdsIdRoute = AdsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdsRoute,
} as any)
const AdminDesignSystemRoute = AdminDesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => AdminRoute,
} as any)
const CategoriesIdIndexRoute = CategoriesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CategoriesIdRoute,
} as any)
const CategoriesIdSubIdRoute = CategoriesIdSubIdRouteImport.update({
  id: '/$subId',
  path: '/$subId',
  getParentRoute: () => CategoriesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ads': typeof AdsRouteWithChildren
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/communities': typeof CommunitiesRouteWithChildren
  '/diag': typeof DiagRoute
  '/favorites': typeof FavoritesRoute
  '/feed': typeof FeedRoute
  '/friends': typeof FriendsRoute
  '/help': typeof HelpRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/messenger': typeof MessengerRoute
  '/my-ads': typeof MyAdsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/recover': typeof RecoverRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/subscription': typeof SubscriptionRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/design-system': typeof AdminDesignSystemRoute
  '/ads/$id': typeof AdsIdRoute
  '/ads/new': typeof AdsNewRoute
  '/categories/$id': typeof CategoriesIdRouteWithChildren
  '/channel/$id': typeof ChannelIdRoute
  '/communities/$id': typeof CommunitiesIdRoute
  '/info/$slug': typeof InfoSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/rules': typeof LegalRulesRoute
  '/reviews/$id': typeof ReviewsIdRoute
  '/reviews/upload': typeof ReviewsUploadRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/history': typeof SettingsHistoryRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/rating': typeof SettingsRatingRoute
  '/settings/requisites': typeof SettingsRequisitesRoute
  '/settings/wallet': typeof SettingsWalletRoute
  '/user/$id': typeof UserIdRoute
  '/ads/': typeof AdsIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/channels/': typeof ChannelsIndexRoute
  '/communities/': typeof CommunitiesIndexRoute
  '/reviews/': typeof ReviewsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/categories/$id/$subId': typeof CategoriesIdSubIdRoute
  '/categories/$id/': typeof CategoriesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/diag': typeof DiagRoute
  '/favorites': typeof FavoritesRoute
  '/feed': typeof FeedRoute
  '/friends': typeof FriendsRoute
  '/help': typeof HelpRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/messenger': typeof MessengerRoute
  '/my-ads': typeof MyAdsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/recover': typeof RecoverRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/subscription': typeof SubscriptionRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/design-system': typeof AdminDesignSystemRoute
  '/ads/$id': typeof AdsIdRoute
  '/ads/new': typeof AdsNewRoute
  '/channel/$id': typeof ChannelIdRoute
  '/communities/$id': typeof CommunitiesIdRoute
  '/info/$slug': typeof InfoSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/rules': typeof LegalRulesRoute
  '/reviews/$id': typeof ReviewsIdRoute
  '/reviews/upload': typeof ReviewsUploadRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/history': typeof SettingsHistoryRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/rating': typeof SettingsRatingRoute
  '/settings/requisites': typeof SettingsRequisitesRoute
  '/settings/wallet': typeof SettingsWalletRoute
  '/user/$id': typeof UserIdRoute
  '/ads': typeof AdsIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/channels': typeof ChannelsIndexRoute
  '/communities': typeof CommunitiesIndexRoute
  '/reviews': typeof ReviewsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/categories/$id/$subId': typeof CategoriesIdSubIdRoute
  '/categories/$id': typeof CategoriesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ads': typeof AdsRouteWithChildren
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/communities': typeof CommunitiesRouteWithChildren
  '/diag': typeof DiagRoute
  '/favorites': typeof FavoritesRoute
  '/feed': typeof FeedRoute
  '/friends': typeof FriendsRoute
  '/help': typeof HelpRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/messenger': typeof MessengerRoute
  '/my-ads': typeof MyAdsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/recover': typeof RecoverRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/subscription': typeof SubscriptionRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/design-system': typeof AdminDesignSystemRoute
  '/ads/$id': typeof AdsIdRoute
  '/ads/new': typeof AdsNewRoute
  '/categories/$id': typeof CategoriesIdRouteWithChildren
  '/channel/$id': typeof ChannelIdRoute
  '/communities/$id': typeof CommunitiesIdRoute
  '/info/$slug': typeof InfoSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/rules': typeof LegalRulesRoute
  '/reviews/$id': typeof ReviewsIdRoute
  '/reviews/upload': typeof ReviewsUploadRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/history': typeof SettingsHistoryRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/rating': typeof SettingsRatingRoute
  '/settings/requisites': typeof SettingsRequisitesRoute
  '/settings/wallet': typeof SettingsWalletRoute
  '/user/$id': typeof UserIdRoute
  '/ads/': typeof AdsIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/channels/': typeof ChannelsIndexRoute
  '/communities/': typeof CommunitiesIndexRoute
  '/reviews/': typeof ReviewsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/categories/$id/$subId': typeof CategoriesIdSubIdRoute
  '/categories/$id/': typeof CategoriesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ads'
    | '/auth'
    | '/categories'
    | '/communities'
    | '/diag'
    | '/favorites'
    | '/feed'
    | '/friends'
    | '/help'
    | '/landing'
    | '/login'
    | '/messenger'
    | '/my-ads'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/recover'
    | '/register'
    | '/reset-password'
    | '/reviews'
    | '/settings'
    | '/subscription'
    | '/verify-email'
    | '/admin/design-system'
    | '/ads/$id'
    | '/ads/new'
    | '/categories/$id'
    | '/channel/$id'
    | '/communities/$id'
    | '/info/$slug'
    | '/legal/privacy'
    | '/legal/rules'
    | '/reviews/$id'
    | '/reviews/upload'
    | '/settings/account'
    | '/settings/history'
    | '/settings/notifications'
    | '/settings/rating'
    | '/settings/requisites'
    | '/settings/wallet'
    | '/user/$id'
    | '/ads/'
    | '/categories/'
    | '/channels/'
    | '/communities/'
    | '/reviews/'
    | '/settings/'
    | '/categories/$id/$subId'
    | '/categories/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/diag'
    | '/favorites'
    | '/feed'
    | '/friends'
    | '/help'
    | '/landing'
    | '/login'
    | '/messenger'
    | '/my-ads'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/recover'
    | '/register'
    | '/reset-password'
    | '/subscription'
    | '/verify-email'
    | '/admin/design-system'
    | '/ads/$id'
    | '/ads/new'
    | '/channel/$id'
    | '/communities/$id'
    | '/info/$slug'
    | '/legal/privacy'
    | '/legal/rules'
    | '/reviews/$id'
    | '/reviews/upload'
    | '/settings/account'
    | '/settings/history'
    | '/settings/notifications'
    | '/settings/rating'
    | '/settings/requisites'
    | '/settings/wallet'
    | '/user/$id'
    | '/ads'
    | '/categories'
    | '/channels'
    | '/communities'
    | '/reviews'
    | '/settings'
    | '/categories/$id/$subId'
    | '/categories/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ads'
    | '/auth'
    | '/categories'
    | '/communities'
    | '/diag'
    | '/favorites'
    | '/feed'
    | '/friends'
    | '/help'
    | '/landing'
    | '/login'
    | '/messenger'
    | '/my-ads'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/recover'
    | '/register'
    | '/reset-password'
    | '/reviews'
    | '/settings'
    | '/subscription'
    | '/verify-email'
    | '/admin/design-system'
    | '/ads/$id'
    | '/ads/new'
    | '/categories/$id'
    | '/channel/$id'
    | '/communities/$id'
    | '/info/$slug'
    | '/legal/privacy'
    | '/legal/rules'
    | '/reviews/$id'
    | '/reviews/upload'
    | '/settings/account'
    | '/settings/history'
    | '/settings/notifications'
    | '/settings/rating'
    | '/settings/requisites'
    | '/settings/wallet'
    | '/user/$id'
    | '/ads/'
    | '/categories/'
    | '/channels/'
    | '/communities/'
    | '/reviews/'
    | '/settings/'
    | '/categories/$id/$subId'
    | '/categories/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdsRoute: typeof AdsRouteWithChildren
  AuthRoute: typeof AuthRoute
  CategoriesRoute: typeof CategoriesRouteWithChildren
  CommunitiesRoute: typeof CommunitiesRouteWithChildren
  DiagRoute: typeof DiagRoute
  FavoritesRoute: typeof FavoritesRoute
  FeedRoute: typeof FeedRoute
  FriendsRoute: typeof FriendsRoute
  HelpRoute: typeof HelpRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  MessengerRoute: typeof MessengerRoute
  MyAdsRoute: typeof MyAdsRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  RecoverRoute: typeof RecoverRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReviewsRoute: typeof ReviewsRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  SubscriptionRoute: typeof SubscriptionRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ChannelIdRoute: typeof ChannelIdRoute
  InfoSlugRoute: typeof InfoSlugRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRulesRoute: typeof LegalRulesRoute
  UserIdRoute: typeof UserIdRoute
  ChannelsIndexRoute: typeof ChannelsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover': {
      id: '/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof RecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-ads': {
      id: '/my-ads'
      path: '/my-ads'
      fullPath: '/my-ads'
      preLoaderRoute: typeof MyAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messenger': {
      id: '/messenger'
      path: '/messenger'
      fullPath: '/messenger'
      preLoaderRoute: typeof MessengerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diag': {
      id: '/diag'
      path: '/diag'
      fullPath: '/diag'
      preLoaderRoute: typeof DiagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities': {
      id: '/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof CommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads': {
      id: '/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/reviews/': {
      id: '/reviews/'
      path: '/'
      fullPath: '/reviews/'
      preLoaderRoute: typeof ReviewsIndexRouteImport
      parentRoute: typeof ReviewsRoute
    }
    '/communities/': {
      id: '/communities/'
      path: '/'
      fullPath: '/communities/'
      preLoaderRoute: typeof CommunitiesIndexRouteImport
      parentRoute: typeof CommunitiesRoute
    }
    '/channels/': {
      id: '/channels/'
      path: '/channels'
      fullPath: '/channels/'
      preLoaderRoute: typeof ChannelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof CategoriesRoute
    }
    '/ads/': {
      id: '/ads/'
      path: '/'
      fullPath: '/ads/'
      preLoaderRoute: typeof AdsIndexRouteImport
      parentRoute: typeof AdsRoute
    }
    '/user/$id': {
      id: '/user/$id'
      path: '/user/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof UserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/wallet': {
      id: '/settings/wallet'
      path: '/wallet'
      fullPath: '/settings/wallet'
      preLoaderRoute: typeof SettingsWalletRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/requisites': {
      id: '/settings/requisites'
      path: '/requisites'
      fullPath: '/settings/requisites'
      preLoaderRoute: typeof SettingsRequisitesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/rating': {
      id: '/settings/rating'
      path: '/rating'
      fullPath: '/settings/rating'
      preLoaderRoute: typeof SettingsRatingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/history': {
      id: '/settings/history'
      path: '/history'
      fullPath: '/settings/history'
      preLoaderRoute: typeof SettingsHistoryRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/reviews/upload': {
      id: '/reviews/upload'
      path: '/upload'
      fullPath: '/reviews/upload'
      preLoaderRoute: typeof ReviewsUploadRouteImport
      parentRoute: typeof ReviewsRoute
    }
    '/reviews/$id': {
      id: '/reviews/$id'
      path: '/$id'
      fullPath: '/reviews/$id'
      preLoaderRoute: typeof ReviewsIdRouteImport
      parentRoute: typeof ReviewsRoute
    }
    '/legal/rules': {
      id: '/legal/rules'
      path: '/legal/rules'
      fullPath: '/legal/rules'
      preLoaderRoute: typeof LegalRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/$slug': {
      id: '/info/$slug'
      path: '/info/$slug'
      fullPath: '/info/$slug'
      preLoaderRoute: typeof InfoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/$id': {
      id: '/communities/$id'
      path: '/$id'
      fullPath: '/communities/$id'
      preLoaderRoute: typeof CommunitiesIdRouteImport
      parentRoute: typeof CommunitiesRoute
    }
    '/channel/$id': {
      id: '/channel/$id'
      path: '/channel/$id'
      fullPath: '/channel/$id'
      preLoaderRoute: typeof ChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$id': {
      id: '/categories/$id'
      path: '/$id'
      fullPath: '/categories/$id'
      preLoaderRoute: typeof CategoriesIdRouteImport
      parentRoute: typeof CategoriesRoute
    }
    '/ads/new': {
      id: '/ads/new'
      path: '/new'
      fullPath: '/ads/new'
      preLoaderRoute: typeof AdsNewRouteImport
      parentRoute: typeof AdsRoute
    }
    '/ads/$id': {
      id: '/ads/$id'
      path: '/$id'
      fullPath: '/ads/$id'
      preLoaderRoute: typeof AdsIdRouteImport
      parentRoute: typeof AdsRoute
    }
    '/admin/design-system': {
      id: '/admin/design-system'
      path: '/design-system'
      fullPath: '/admin/design-system'
      preLoaderRoute: typeof AdminDesignSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/categories/$id/': {
      id: '/categories/$id/'
      path: '/'
      fullPath: '/categories/$id/'
      preLoaderRoute: typeof CategoriesIdIndexRouteImport
      parentRoute: typeof CategoriesIdRoute
    }
    '/categories/$id/$subId': {
      id: '/categories/$id/$subId'
      path: '/$subId'
      fullPath: '/categories/$id/$subId'
      preLoaderRoute: typeof CategoriesIdSubIdRouteImport
      parentRoute: typeof CategoriesIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDesignSystemRoute: typeof AdminDesignSystemRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDesignSystemRoute: AdminDesignSystemRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AdsRouteChildren {
  AdsIdRoute: typeof AdsIdRoute
  AdsNewRoute: typeof AdsNewRoute
  AdsIndexRoute: typeof AdsIndexRoute
}

const AdsRouteChildren: AdsRouteChildren = {
  AdsIdRoute: AdsIdRoute,
  AdsNewRoute: AdsNewRoute,
  AdsIndexRoute: AdsIndexRoute,
}

const AdsRouteWithChildren = AdsRoute._addFileChildren(AdsRouteChildren)

interface CategoriesIdRouteChildren {
  CategoriesIdSubIdRoute: typeof CategoriesIdSubIdRoute
  CategoriesIdIndexRoute: typeof CategoriesIdIndexRoute
}

const CategoriesIdRouteChildren: CategoriesIdRouteChildren = {
  CategoriesIdSubIdRoute: CategoriesIdSubIdRoute,
  CategoriesIdIndexRoute: CategoriesIdIndexRoute,
}

const CategoriesIdRouteWithChildren = CategoriesIdRoute._addFileChildren(
  CategoriesIdRouteChildren,
)

interface CategoriesRouteChildren {
  CategoriesIdRoute: typeof CategoriesIdRouteWithChildren
  CategoriesIndexRoute: typeof CategoriesIndexRoute
}

const CategoriesRouteChildren: CategoriesRouteChildren = {
  CategoriesIdRoute: CategoriesIdRouteWithChildren,
  CategoriesIndexRoute: CategoriesIndexRoute,
}

const CategoriesRouteWithChildren = CategoriesRoute._addFileChildren(
  CategoriesRouteChildren,
)

interface CommunitiesRouteChildren {
  CommunitiesIdRoute: typeof CommunitiesIdRoute
  CommunitiesIndexRoute: typeof CommunitiesIndexRoute
}

const CommunitiesRouteChildren: CommunitiesRouteChildren = {
  CommunitiesIdRoute: CommunitiesIdRoute,
  CommunitiesIndexRoute: CommunitiesIndexRoute,
}

const CommunitiesRouteWithChildren = CommunitiesRoute._addFileChildren(
  CommunitiesRouteChildren,
)

interface ReviewsRouteChildren {
  ReviewsIdRoute: typeof ReviewsIdRoute
  ReviewsUploadRoute: typeof ReviewsUploadRoute
  ReviewsIndexRoute: typeof ReviewsIndexRoute
}

const ReviewsRouteChildren: ReviewsRouteChildren = {
  ReviewsIdRoute: ReviewsIdRoute,
  ReviewsUploadRoute: ReviewsUploadRoute,
  ReviewsIndexRoute: ReviewsIndexRoute,
}

const ReviewsRouteWithChildren =
  ReviewsRoute._addFileChildren(ReviewsRouteChildren)

interface SettingsRouteChildren {
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsHistoryRoute: typeof SettingsHistoryRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsRatingRoute: typeof SettingsRatingRoute
  SettingsRequisitesRoute: typeof SettingsRequisitesRoute
  SettingsWalletRoute: typeof SettingsWalletRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsHistoryRoute: SettingsHistoryRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsRatingRoute: SettingsRatingRoute,
  SettingsRequisitesRoute: SettingsRequisitesRoute,
  SettingsWalletRoute: SettingsWalletRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdsRoute: AdsRouteWithChildren,
  AuthRoute: AuthRoute,
  CategoriesRoute: CategoriesRouteWithChildren,
  CommunitiesRoute: CommunitiesRouteWithChildren,
  DiagRoute: DiagRoute,
  FavoritesRoute: FavoritesRoute,
  FeedRoute: FeedRoute,
  FriendsRoute: FriendsRoute,
  HelpRoute: HelpRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  MessengerRoute: MessengerRoute,
  MyAdsRoute: MyAdsRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  RecoverRoute: RecoverRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReviewsRoute: ReviewsRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  SubscriptionRoute: SubscriptionRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ChannelIdRoute: ChannelIdRoute,
  InfoSlugRoute: InfoSlugRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRulesRoute: LegalRulesRoute,
  UserIdRoute: UserIdRoute,
  ChannelsIndexRoute: ChannelsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
